### ISSUE TITLE
hmac.compare_digest does not exist in Python < 2.7.7

### ISSUE THREAD

**Issue by kpriceyahoo** [carlos-jenkins/python-github-webhooks#4]
One issue I ran into with this webhooks script is that hmac.compare_digest is new in 2.7.7, and for legacy reasons I'm stuck on 2.6.

I have a few different ways to solve this problem in a general way, and I wanted to get your feedback before I submit a pull request.

Option 1: fall back to a simple string comparison if hmac.compare_digest is unavailable. This is functionally equivalent, but simply fails to provide protection against a timing attack. (It's not clear to me that a timing attack is even a concern, given the inherit network latency involved, so this may be perfectly safe.)

Option 2: have an option, disabled by default, to allow the fallback. This is what I have implemented locally. Code snippet below.

Option 3: have a fallback to a python-based version of compare_digest. This would be slower than the C implementation in the standard library, but would provide the same protection. It would also require adding a python-fallback to the repo, as I don't think there's one available in a pip package anywhere.

The code for option 2 would look something like:

``` python
        # HMAC requires the key to be bytes, but data is string
        mac = hmac.new(str(secret), msg=request.data, digestmod=sha1)

        # Python prior to 2.7.7 does not have hmac.compare_digest
        try:
            if not hmac.compare_digest(str(mac.hexdigest()), str(signature)):
                abort(403)
        except AttributeError as e:
            # What compare_digest provides is protection against timing attacks, but if
            # the user is okay with not having this protection, let's let them allow a
            # trivial fallback
            if not config.get('allow_insecure_compare_digest', False):
                logging.error('Could not call hmac.compare_digest; are you running python < 2.7.7?', exc_info=True)
                abort(500)

            if not str(mac.hexdigest()) == str(signature):
                abort(403)
```

Let me know your thoughts, and I can prepare a pull request.

**Comment by PHLAK** [comment]
+1 for this.  Tried running this on an Ubuntu 14.04 server (with python 2.7.6) and it did not work.

**Comment by kpriceyahoo** [comment]
@PHLAK: If you want a quick kludge, just replace "hmac.compare_digest(str(mac.hexdigest()), str(signature))" with "str(mac.hexdigest()) == str(signature)" and it'll work fine.

**Comment by kpriceyahoo** [comment]
I went with a modified version of option 2 and just enabled the fallback automatically based on the Python version. Since the secret feature is unusable for earlier versions of python otherwise, I don't see any reason to add the option.
